# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddEditCoffeeForm(object):
    def setupUi(self, AddEditCoffeeForm):
        AddEditCoffeeForm.setObjectName("AddEditCoffeeForm")
        AddEditCoffeeForm.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(AddEditCoffeeForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.nameInput = QtWidgets.QLineEdit(parent=AddEditCoffeeForm)
        self.nameInput.setObjectName("nameInput")
        self.verticalLayout.addWidget(self.nameInput)
        self.roastLevelInput = QtWidgets.QLineEdit(parent=AddEditCoffeeForm)
        self.roastLevelInput.setObjectName("roastLevelInput")
        self.verticalLayout.addWidget(self.roastLevelInput)
        self.groundOrBeansInput = QtWidgets.QLineEdit(parent=AddEditCoffeeForm)
        self.groundOrBeansInput.setObjectName("groundOrBeansInput")
        self.verticalLayout.addWidget(self.groundOrBeansInput)
        self.tasteDescriptionInput = QtWidgets.QLineEdit(parent=AddEditCoffeeForm)
        self.tasteDescriptionInput.setObjectName("tasteDescriptionInput")
        self.verticalLayout.addWidget(self.tasteDescriptionInput)
        self.priceInput = QtWidgets.QLineEdit(parent=AddEditCoffeeForm)
        self.priceInput.setObjectName("priceInput")
        self.verticalLayout.addWidget(self.priceInput)
        self.packageVolumeInput = QtWidgets.QLineEdit(parent=AddEditCoffeeForm)
        self.packageVolumeInput.setObjectName("packageVolumeInput")
        self.verticalLayout.addWidget(self.packageVolumeInput)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.saveButton = QtWidgets.QPushButton(parent=AddEditCoffeeForm)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        self.cancelButton = QtWidgets.QPushButton(parent=AddEditCoffeeForm)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(AddEditCoffeeForm)
        QtCore.QMetaObject.connectSlotsByName(AddEditCoffeeForm)

    def retranslateUi(self, AddEditCoffeeForm):
        _translate = QtCore.QCoreApplication.translate
        AddEditCoffeeForm.setWindowTitle(_translate("AddEditCoffeeForm", "Add/Edit Coffee"))
        self.nameInput.setPlaceholderText(_translate("AddEditCoffeeForm", "Name"))
        self.roastLevelInput.setPlaceholderText(_translate("AddEditCoffeeForm", "Roast Level"))
        self.groundOrBeansInput.setPlaceholderText(_translate("AddEditCoffeeForm", "Ground/Beans"))
        self.tasteDescriptionInput.setPlaceholderText(_translate("AddEditCoffeeForm", "Taste Description"))
        self.priceInput.setPlaceholderText(_translate("AddEditCoffeeForm", "Price"))
        self.packageVolumeInput.setPlaceholderText(_translate("AddEditCoffeeForm", "Package Volume"))
        self.saveButton.setText(_translate("AddEditCoffeeForm", "Save"))
        self.cancelButton.setText(_translate("AddEditCoffeeForm", "Cancel"))
